service: serverless-pg-nestjs

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  stage: ${opt:stage,'dev'}
  region: ${opt:region,'us-east-1'}
  memorySize: 128
  logRetentionInDays: 1
  timeout: 15

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-jetpack
  - serverless-offline
